### ISSUE TITLE
Overriding color

### ISSUE THREAD

**Issue by daGrevis** [haya14busa/vim-operator-flashy#6]
Unfortunately this doesn't help when put in `.vimrc`.

```
hi Flashy guibg=red
```

Plugin is overriding it on load.

When I change color manually from command mode, it works.

**Comment by haya14busa** [comment]
Thank you for the report. I fixed it.

**Comment by daGrevis** [comment]
Thanks for the fix!

**Comment by eternauta1337** [comment]
I believe the problem still exists, so I suggest that this issue is reopened.

In vimrc (doesn't work):
```highligh Flashy guibg=red```

In command mode (works fine):
```:highlight Flashy guibg=red```

Let me know if you need any more info.
